/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include "stdio.h"

main () {
	long i, j, k, sum = 0, temp;
	for ( i = 1, j = 2; i < 4000000; k = i, i = j, j += k ) {
		if ( i % 2 == 0 ) sum += i;
		printf("%d %d\n", i, sum);
	}
	printf("%d\n", sum);
}
